version: '3.7'

services:
  prod:
    container_name: project_production
    restart: unless-stopped
    build:
      context: ./
    ports:
      - '8000:8080'
    command: yarn start
  dev:
    container_name: project_development
    restart: unless-stopped
    build:
      context: ./
      target: base
    volumes:
      - ./src:/base/src
    ports:
      - '8080:8080'
    command: yarn dev
